# Generated by Django 5.2.3 on 2025-06-20 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('visitor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='visform.visitor')),
            ],
        ),
        migrations.CreateModel(
            name='RejectedVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejected_at', models.DateTimeField(auto_now_add=True)),
                ('visitor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='visform.visitor')),
            ],
        ),
        migrations.CreateModel(
            name='RescheduledVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_date', models.DateField()),
                ('new_time', models.TimeField()),
                ('rescheduled_at', models.DateTimeField(auto_now_add=True)),
                ('visitor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='visform.visitor')),
            ],
        ),
    ]
