# Generated by Django 5.2.3 on 2025-06-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('category', models.CharField(choices=[('Parent', 'Parent'), ('Student', 'Student'), ('Staff', 'Staff'), ('General', 'General')], max_length=20)),
                ('designation', models.CharField(choices=[('HOD', 'HOD'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor')], max_length=30)),
                ('phone', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('reason', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
