# Generated by Django 5.2.3 on 2025-06-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('rescheduled', 'Rescheduled')], default='pending', max_length=20),
        ),
    ]
